services:
  seaals:
    build: .
    user: seaals
    ports:
      - 8080:8080
    environment:
      DB_PATH: /opt/seaals/data/seaals.db
      BASE_PATH: /opt/seaals/data
    volumes:
      - sealdata:/opt/seaals/data
    command: serve
volumes:
  sealdata:
