openapi: "3.1.0"
info:
  version: 1.0.0
  title: Minimal seaals API server
paths:
  /seal:
    get:
      summary: Get a random Seal
      parameters:
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/filterParam"
      responses:
        "200":
          description: Image of a seal
          content:
            image/*:
              type: string
              format: binary
            application/json:
              schema:
                $ref: "#/components/schemas/Seal"
  /seal/says/{text}:
    get:
      summary: Get a random Seal saying something
      parameters:
        - in: path
          name: text
          schema:
            type: string
          required: true
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/filterParam"
        - $ref: "#/components/parameters/positionParam"
        - $ref: "#/components/parameters/fontSizeParam"
        - $ref: "#/components/parameters/fontColourParam"
        - $ref: "#/components/parameters/borderSizeParam"
        - $ref: "#/components/parameters/borderColourParam"
components:
  parameters:
    tagParam:
      in: query
      name: tag
      schema:
        type: string
      required: false
      description: Tag of the Seal
    filterParam:
      in: query
      name: filter
      schema:
        type: string
        enum:
          - monochrome
          - invert
          - funky
      required: false
      description: Filter to apply to the image
    positionParam:
      in: query
      name: position
      schema:
        type: string
        enum:
          - top
          - bottom
          - left
          - right
      required: false
      description: Position of the caption text on the image
    fontSizeParam:
      in: query
      name: fontSize
      schema:
        type: integer
        minimum: 0
        default: 48
      required: false
      description: Size of the caption text
    fontColourParam:
      in: query
      name: fontColour
      schema:
        type: string
        default: white
      required: false
      description: Colour of the caption text
    borderColourParam:
      in: query
      name: borderColour
      schema:
        type: string
        default: black
      required: false
      description: Colour of the caption border
    borderSizeParam:
      in: query
      name: borderSize
      schema:
        type: integer
        minimum: 0
        default: 6
      required: false
      description: Thickness of the caption border
  schemas:
    Seal:
      type: object
      required:
        - tags
      properties:
        id:
          type: string
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        mimeType:
          type: string
        createdAt:
          type: string
    Tag:
      type: string
