openapi: "3.2.0"
info:
  version: 1.0.0
  title: SEAaLS API server
paths:
  /api/seal:
    get:
      summary: Get a JSON reprentation of a random Seal
      tags:
        - API
      parameters:
        - $ref: "#/components/parameters/tagParam"
      responses:
        "200":
          description: JSON data of a seal
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seal"
  /api/seal/{id}:
    get:
      summary: Get a JSON reprentation of a Seal by their ID
      tags:
        - API
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: JSON data of a seal
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seal"
  /seal:
    get:
      summary: Get a random Seal
      tags:
        - Seals
      parameters:
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/filterParam"
        - $ref: "#/components/parameters/permalinkParam"
      responses:
        "200":
          description: Image of a seal
          content:
            image/*:
              type: string
              format: binary
        "302":
          description: Redirect to the permalink URL of a random seal with provided parameters
  /seal/{id}:
    get:
      summary: Get a Seal by their ID
      tags:
        - Seals
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
        - $ref: "#/components/parameters/filterParam"
      responses:
        "200":
          description: Image of a seal
          content:
            image/*:
              type: string
              format: binary
  /seal/says/{text}:
    get:
      summary: Get a random Seal saying something
      tags:
        - Seals
      parameters:
        - in: path
          name: text
          schema:
            type: string
          required: true
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/filterParam"
        - $ref: "#/components/parameters/positionParam"
        - $ref: "#/components/parameters/fontSizeParam"
        - $ref: "#/components/parameters/fontColourParam"
        - $ref: "#/components/parameters/borderSizeParam"
        - $ref: "#/components/parameters/borderColourParam"
        - $ref: "#/components/parameters/permalinkParam"
      responses:
        "200":
          description: Image of a seal saying something
          content:
            image/*:
              type: string
              format: binary
        "302":
          description: Redirect to the permalink URL of a random seal with provided parameters
  /seal/{id}/says/{text}:
    get:
      summary: Get a random Seal saying something
      tags:
        - Seals
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
        - in: path
          name: text
          schema:
            type: string
          required: true
        - $ref: "#/components/parameters/filterParam"
        - $ref: "#/components/parameters/positionParam"
        - $ref: "#/components/parameters/fontSizeParam"
        - $ref: "#/components/parameters/fontColourParam"
        - $ref: "#/components/parameters/borderSizeParam"
        - $ref: "#/components/parameters/borderColourParam"
      responses:
        "200":
          description: Image of a seal saying something
          content:
            image/*:
              type: string
              format: binary
components:
  parameters:
    tagParam:
      in: query
      name: tag
      schema:
        type: string
      required: false
      description: Tag of the Seal
    filterParam:
      in: query
      name: filter
      schema:
        type: string
        enum:
          - monochrome
          - invert
          - funky
      required: false
      description: Filter to apply to the image
    positionParam:
      in: query
      name: position
      schema:
        type: string
        enum:
          - top
          - bottom
          - left
          - right
      required: false
      description: Position of the caption text on the image
    fontSizeParam:
      in: query
      name: fontSize
      schema:
        type: integer
        minimum: 0
        default: 48
      required: false
      description: Size of the caption text
    fontColourParam:
      in: query
      name: fontColour
      schema:
        type: string
        default: white
      required: false
      description: Colour of the caption text
    borderColourParam:
      in: query
      name: borderColour
      schema:
        type: string
        default: black
      required: false
      description: Colour of the caption border
    borderSizeParam:
      in: query
      name: borderSize
      schema:
        type: integer
        minimum: 0
        default: 6
      required: false
      description: Thickness of the caption border
    permalinkParam:
      in: query
      name: permalink
      schema:
        type: boolean
        default: false
      required: false
      description: Redirect to the permalink URL of the image with provided parameters
  schemas:
    Seal:
      type: object
      required:
        - id
        - permalink
        - tags
        - mimeType
        - createdAt
      properties:
        id:
          type: string
        permalink:
          type: string
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        mimeType:
          type: string
        createdAt:
          type: string
    Tag:
      type: string
