// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Seal struct {
	ID        int64     `json:"id"`
	Path      string    `json:"path"`
	MimeType  string    `json:"mime_type"`
	CreatedAt time.Time `json:"created_at"`
}

type SealTag struct {
	ID     int64 `json:"id"`
	SealID int64 `json:"seal_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
