// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seals.sql

package db

import (
	"context"
)

const addSealTag = `-- name: AddSealTag :one
INSERT INTO seal_tags (
  seal_id, tag_id
) VALUES (
  ?, ?
)
RETURNING id, seal_id, tag_id
`

type AddSealTagParams struct {
	SealID int64 `json:"seal_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddSealTag(ctx context.Context, arg AddSealTagParams) (SealTag, error) {
	row := q.db.QueryRowContext(ctx, addSealTag, arg.SealID, arg.TagID)
	var i SealTag
	err := row.Scan(&i.ID, &i.SealID, &i.TagID)
	return i, err
}

const countSeals = `-- name: CountSeals :one
SELECT count(*) FROM seals
`

func (q *Queries) CountSeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSealsByTag = `-- name: CountSealsByTag :one
SELECT count(*) FROM seals
INNER JOIN seal_tags ON seal_tags.seal_id = seals.id
INNER JOIN tags ON seal_tags.tag_id = tags.id
WHERE tags.name = ?
`

func (q *Queries) CountSealsByTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSealsByTag, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeal = `-- name: CreateSeal :one
INSERT INTO seals (
  path, mime_type
) VALUES (
  ?, ?
)
RETURNING id, path, mime_type, created_at
`

type CreateSealParams struct {
	Path     string `json:"path"`
	MimeType string `json:"mime_type"`
}

func (q *Queries) CreateSeal(ctx context.Context, arg CreateSealParams) (Seal, error) {
	row := q.db.QueryRowContext(ctx, createSeal, arg.Path, arg.MimeType)
	var i Seal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSeal = `-- name: DeleteSeal :exec
DELETE FROM seals
WHERE id = ?
`

func (q *Queries) DeleteSeal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSeal, id)
	return err
}

const getSeal = `-- name: GetSeal :one
SELECT id, path, mime_type, created_at FROM seals
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSeal(ctx context.Context, id int64) (Seal, error) {
	row := q.db.QueryRowContext(ctx, getSeal, id)
	var i Seal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const getSealByPath = `-- name: GetSealByPath :one
SELECT id, path, mime_type, created_at FROM seals
WHERE path LIKE ? LIMIT 1
`

func (q *Queries) GetSealByPath(ctx context.Context, path string) (Seal, error) {
	row := q.db.QueryRowContext(ctx, getSealByPath, path)
	var i Seal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const listSealTags = `-- name: ListSealTags :many
SELECT tags.id, tags.name FROM tags
INNER JOIN seal_tags ON seal_tags.tag_id = tags.id
WHERE seal_tags.seal_id = ?
`

func (q *Queries) ListSealTags(ctx context.Context, sealID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listSealTags, sealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeals = `-- name: ListSeals :many
SELECT id, path, mime_type, created_at FROM seals
ORDER BY id
`

func (q *Queries) ListSeals(ctx context.Context) ([]Seal, error) {
	rows, err := q.db.QueryContext(ctx, listSeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seal
	for rows.Next() {
		var i Seal
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSealsWithTag = `-- name: ListSealsWithTag :many
SELECT seals.id, seals.path, seals.mime_type, seals.created_at FROM seals
INNER JOIN seal_tags ON seal_tags.seal_id = seals.id
INNER JOIN tags ON seal_tags.tag_id = tags.id
WHERE tags.name = ?
`

func (q *Queries) ListSealsWithTag(ctx context.Context, name string) ([]Seal, error) {
	rows, err := q.db.QueryContext(ctx, listSealsWithTag, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seal
	for rows.Next() {
		var i Seal
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomSeal = `-- name: RandomSeal :one
SELECT id, path, mime_type, created_at from seals
ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) RandomSeal(ctx context.Context) (Seal, error) {
	row := q.db.QueryRowContext(ctx, randomSeal)
	var i Seal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const randomSealWithTag = `-- name: RandomSealWithTag :one
SELECT seals.id, seals.path, seals.mime_type, seals.created_at FROM seals
INNER JOIN seal_tags ON seal_tags.seal_id = seals.id
INNER JOIN tags ON seal_tags.tag_id = tags.id
WHERE tags.name = ?
ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) RandomSealWithTag(ctx context.Context, name string) (Seal, error) {
	row := q.db.QueryRowContext(ctx, randomSealWithTag, name)
	var i Seal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const updateSeal = `-- name: UpdateSeal :one
UPDATE seals
set path = ?,
mime_type = ?
WHERE id = ?
RETURNING id, path, mime_type, created_at
`

type UpdateSealParams struct {
	Path     string `json:"path"`
	MimeType string `json:"mime_type"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateSeal(ctx context.Context, arg UpdateSealParams) (Seal, error) {
	row := q.db.QueryRowContext(ctx, updateSeal, arg.Path, arg.MimeType, arg.ID)
	var i Seal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}
