// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPopularTags = `-- name: GetPopularTags :many
SELECT tags.name,COUNT(tag_id) as "count"
FROM seal_tags INNER JOIN tags ON tags.id == tag_id
WHERE tags.name != 'jpeg' AND tags.name != 'png' AND tags.name != 'gif'
GROUP BY tag_id ORDER BY "count" DESC LIMIT 10
`

type GetPopularTagsRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetPopularTags(ctx context.Context) ([]GetPopularTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularTagsRow
	for rows.Next() {
		var i GetPopularTagsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name FROM tags
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagWithName = `-- name: GetTagWithName :one
SELECT id, name from tags
WHERE name = ?
`

func (q *Queries) GetTagWithName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagWithName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
