// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// Defines values for FilterParam.
const (
	FilterParamFunky      FilterParam = "funky"
	FilterParamInvert     FilterParam = "invert"
	FilterParamMonochrome FilterParam = "monochrome"
)

// Defines values for GetSealParamsFilter.
const (
	GetSealParamsFilterFunky      GetSealParamsFilter = "funky"
	GetSealParamsFilterInvert     GetSealParamsFilter = "invert"
	GetSealParamsFilterMonochrome GetSealParamsFilter = "monochrome"
)

// Defines values for GetSealSaysTextParamsFilter.
const (
	Funky      GetSealSaysTextParamsFilter = "funky"
	Invert     GetSealSaysTextParamsFilter = "invert"
	Monochrome GetSealSaysTextParamsFilter = "monochrome"
)

// Seal defines model for Seal.
type Seal struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	Id        *string `json:"id,omitempty"`
	MimeType  *string `json:"mimeType,omitempty"`
	Tags      []Tag   `json:"tags"`
}

// Tag defines model for Tag.
type Tag = string

// FilterParam defines model for filterParam.
type FilterParam string

// TagParam defines model for tagParam.
type TagParam = string

// GetSealParams defines parameters for GetSeal.
type GetSealParams struct {
	// Tag Tag of the Seal
	Tag *TagParam `form:"tag,omitempty" json:"tag,omitempty"`

	// Filter Filter to apply to the image
	Filter *GetSealParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSealParamsFilter defines parameters for GetSeal.
type GetSealParamsFilter string

// GetSealSaysTextParams defines parameters for GetSealSaysText.
type GetSealSaysTextParams struct {
	// Tag Tag of the Seal
	Tag *TagParam `form:"tag,omitempty" json:"tag,omitempty"`

	// Filter Filter to apply to the image
	Filter *GetSealSaysTextParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSealSaysTextParamsFilter defines parameters for GetSealSaysText.
type GetSealSaysTextParamsFilter string
