// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// Defines values for FilterParam.
const (
	FilterParamFunky      FilterParam = "funky"
	FilterParamInvert     FilterParam = "invert"
	FilterParamMonochrome FilterParam = "monochrome"
)

// Defines values for PositionParam.
const (
	PositionParamBottom PositionParam = "bottom"
	PositionParamLeft   PositionParam = "left"
	PositionParamRight  PositionParam = "right"
	PositionParamTop    PositionParam = "top"
)

// Defines values for GetSealParamsFilter.
const (
	GetSealParamsFilterFunky      GetSealParamsFilter = "funky"
	GetSealParamsFilterInvert     GetSealParamsFilter = "invert"
	GetSealParamsFilterMonochrome GetSealParamsFilter = "monochrome"
)

// Defines values for GetSealSaysTextParamsFilter.
const (
	Funky      GetSealSaysTextParamsFilter = "funky"
	Invert     GetSealSaysTextParamsFilter = "invert"
	Monochrome GetSealSaysTextParamsFilter = "monochrome"
)

// Defines values for GetSealSaysTextParamsPosition.
const (
	GetSealSaysTextParamsPositionBottom GetSealSaysTextParamsPosition = "bottom"
	GetSealSaysTextParamsPositionLeft   GetSealSaysTextParamsPosition = "left"
	GetSealSaysTextParamsPositionRight  GetSealSaysTextParamsPosition = "right"
	GetSealSaysTextParamsPositionTop    GetSealSaysTextParamsPosition = "top"
)

// Seal defines model for Seal.
type Seal struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`
	MimeType  string `json:"mimeType"`
	Tags      []Tag  `json:"tags"`
}

// Tag defines model for Tag.
type Tag = string

// BorderColourParam defines model for borderColourParam.
type BorderColourParam = string

// BorderSizeParam defines model for borderSizeParam.
type BorderSizeParam = int

// FilterParam defines model for filterParam.
type FilterParam string

// FontColourParam defines model for fontColourParam.
type FontColourParam = string

// FontSizeParam defines model for fontSizeParam.
type FontSizeParam = int

// PositionParam defines model for positionParam.
type PositionParam string

// TagParam defines model for tagParam.
type TagParam = string

// GetSealParams defines parameters for GetSeal.
type GetSealParams struct {
	// Tag Tag of the Seal
	Tag *TagParam `form:"tag,omitempty" json:"tag,omitempty"`

	// Filter Filter to apply to the image
	Filter *GetSealParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSealParamsFilter defines parameters for GetSeal.
type GetSealParamsFilter string

// GetSealSaysTextParams defines parameters for GetSealSaysText.
type GetSealSaysTextParams struct {
	// Tag Tag of the Seal
	Tag *TagParam `form:"tag,omitempty" json:"tag,omitempty"`

	// Filter Filter to apply to the image
	Filter *GetSealSaysTextParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`

	// Position Position of the caption text on the image
	Position *GetSealSaysTextParamsPosition `form:"position,omitempty" json:"position,omitempty"`

	// FontSize Size of the caption text
	FontSize *FontSizeParam `form:"fontSize,omitempty" json:"fontSize,omitempty"`

	// FontColour Colour of the caption text
	FontColour *FontColourParam `form:"fontColour,omitempty" json:"fontColour,omitempty"`

	// BorderSize Thickness of the caption border
	BorderSize *BorderSizeParam `form:"borderSize,omitempty" json:"borderSize,omitempty"`

	// BorderColour Colour of the caption border
	BorderColour *BorderColourParam `form:"borderColour,omitempty" json:"borderColour,omitempty"`
}

// GetSealSaysTextParamsFilter defines parameters for GetSealSaysText.
type GetSealSaysTextParamsFilter string

// GetSealSaysTextParamsPosition defines parameters for GetSealSaysText.
type GetSealSaysTextParamsPosition string
