// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a JSON reprentation of a random Seal
	// (GET /api/seal)
	GetApiSeal(c *gin.Context, params GetApiSealParams)
	// Get a JSON reprentation of a Seal by their ID
	// (GET /api/seal/{id})
	GetApiSealId(c *gin.Context, id string)
	// Get a random Seal
	// (GET /seal)
	GetSeal(c *gin.Context, params GetSealParams)
	// Get a random Seal saying something
	// (GET /seal/says/{text})
	GetSealSaysText(c *gin.Context, text string, params GetSealSaysTextParams)
	// Get a Seal by their ID
	// (GET /seal/{id})
	GetSealId(c *gin.Context, id string, params GetSealIdParams)
	// Get a random Seal saying something
	// (GET /seal/{id}/says/{text})
	GetSealIdSaysText(c *gin.Context, id string, text string, params GetSealIdSaysTextParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiSeal operation middleware
func (siw *ServerInterfaceWrapper) GetApiSeal(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiSealParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiSeal(c, params)
}

// GetApiSealId operation middleware
func (siw *ServerInterfaceWrapper) GetApiSealId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiSealId(c, id)
}

// GetSeal operation middleware
func (siw *ServerInterfaceWrapper) GetSeal(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSealParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "permalink" -------------

	err = runtime.BindQueryParameter("form", true, false, "permalink", c.Request.URL.Query(), &params.Permalink)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter permalink: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSeal(c, params)
}

// GetSealSaysText operation middleware
func (siw *ServerInterfaceWrapper) GetSealSaysText(c *gin.Context) {

	var err error

	// ------------- Path parameter "text" -------------
	var text string

	err = runtime.BindStyledParameterWithOptions("simple", "text", c.Param("text"), &text, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter text: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSealSaysTextParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "position" -------------

	err = runtime.BindQueryParameter("form", true, false, "position", c.Request.URL.Query(), &params.Position)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter position: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fontSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "fontSize", c.Request.URL.Query(), &params.FontSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fontSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fontColour" -------------

	err = runtime.BindQueryParameter("form", true, false, "fontColour", c.Request.URL.Query(), &params.FontColour)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fontColour: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "borderSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "borderSize", c.Request.URL.Query(), &params.BorderSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter borderSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "borderColour" -------------

	err = runtime.BindQueryParameter("form", true, false, "borderColour", c.Request.URL.Query(), &params.BorderColour)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter borderColour: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "permalink" -------------

	err = runtime.BindQueryParameter("form", true, false, "permalink", c.Request.URL.Query(), &params.Permalink)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter permalink: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSealSaysText(c, text, params)
}

// GetSealId operation middleware
func (siw *ServerInterfaceWrapper) GetSealId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSealIdParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSealId(c, id, params)
}

// GetSealIdSaysText operation middleware
func (siw *ServerInterfaceWrapper) GetSealIdSaysText(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "text" -------------
	var text string

	err = runtime.BindStyledParameterWithOptions("simple", "text", c.Param("text"), &text, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter text: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSealIdSaysTextParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "position" -------------

	err = runtime.BindQueryParameter("form", true, false, "position", c.Request.URL.Query(), &params.Position)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter position: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fontSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "fontSize", c.Request.URL.Query(), &params.FontSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fontSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fontColour" -------------

	err = runtime.BindQueryParameter("form", true, false, "fontColour", c.Request.URL.Query(), &params.FontColour)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fontColour: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "borderSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "borderSize", c.Request.URL.Query(), &params.BorderSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter borderSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "borderColour" -------------

	err = runtime.BindQueryParameter("form", true, false, "borderColour", c.Request.URL.Query(), &params.BorderColour)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter borderColour: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSealIdSaysText(c, id, text, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/seal", wrapper.GetApiSeal)
	router.GET(options.BaseURL+"/api/seal/:id", wrapper.GetApiSealId)
	router.GET(options.BaseURL+"/seal", wrapper.GetSeal)
	router.GET(options.BaseURL+"/seal/says/:text", wrapper.GetSealSaysText)
	router.GET(options.BaseURL+"/seal/:id", wrapper.GetSealId)
	router.GET(options.BaseURL+"/seal/:id/says/:text", wrapper.GetSealIdSaysText)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWS2/jNhD+K8S0p0JYubtFUfhm9AUXizZYp6cgh4k0krgRH0uOs1UN//eClB9yQvmR",
	"tpsW2JNlDjn8+H3zWkFhlDWaNHuYrsCiQ0VMLv67M64k971pzdJdBUtYLMkXTlqWRsMUeqMwleCGRIFx",
	"XfQHIQMZ9nxYkusgA42KYHrgFTLwRUMKe88VLlsOW1os7iED7mw44dlJXcN6nW0OL+SfNALoupHFvSbv",
	"n4EpuE0j+jYDJbVUSwXTyQ6X1Ew1uQiski3TGEs/RaNgI9DatgsfAZpUWNMIot7fARrS4fobUEabonFG",
	"9WcfyDFkUC31fQe3KdIqo/kZKjL9wWPodh5HFPzYSCYYA3NEv2C6EMi4bN98d1I3S05hK/X9CJ53VEpH",
	"BW812+0Xv797uwUahRQfJTfCOvMgSyrFIJXS0Hee0tgrbD3tIN8Z0xLqHrLxMqAbQXy1MadYFOH3RORt",
	"3Sdjj42FkIXMRkEGLVVBGSfrhtOxx1iPZSrWW4gLwnYEDWN9AOTxDeutMVas6CjUMWcsOZYUVwtHyFTO",
	"OOEgA1kml5VUdB0XE8a9dikrYx3vlUwqfnzpqIIpfJHvq22+QZ1fY3+md4LOYReJc/RhKR2VgXVZQnYQ",
	"L/GGAcZs8Ma9DObuPRUcvIdL0uRJXZloktwG2+LHGb5diNnVXHhyD7EEPZDzvWZfv5q8mgSHxpJGK2EK",
	"b+JSBha5iY/N0crcb4SoKZIe1MCg+7yEKfxMPLNyI/qw5dykqdpvyXfhtL4NFHlrtO9Ffj2ZRK2NZtLx",
	"0lBrZRGvzd/7gH81CKRjmkRokZ7DkP1l8duvokTGELgofL8tA79UCl3XP02giPscWUeacZuLKBzq0qht",
	"tPdRcgOzqzncBi874vKVLNdnsDcvn/IXcyhosU+hGD37cGK3pGMZ9T8kNrgVd12oJdKJ+Q9Jdk+F5N+M",
	"x+zk3uGIcMb2R53pDF1iVc+/Cp+VcQrjKCU1xnr6tDQfSjCPPWxAfwZvJq+f0RB3cR7cjDfFlLzpBAl/",
	"/UDE3GPn81XoZ+tTgi6w89f9+HA6UTZzxvmpkr1ofByMAef4P5i8zjwwnBvPOPJ4Pj/7yIX3vGxyCI+d",
	"1LXwRhE3m67/ktnyFNCR9DnVXf691nJhDnzqipfg+EhnSfJ6SW2alxdVp8u5/jQl7nPZcv+VIvQPFIn1",
	"+q8AAAD//1pDwvkUEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
