// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a random Seal
	// (GET /seal)
	GetSeal(c *gin.Context, params GetSealParams)
	// Get a random Seal saying something
	// (GET /seal/says/{text})
	GetSealSaysText(c *gin.Context, text string, params GetSealSaysTextParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetSeal operation middleware
func (siw *ServerInterfaceWrapper) GetSeal(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSealParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSeal(c, params)
}

// GetSealSaysText operation middleware
func (siw *ServerInterfaceWrapper) GetSealSaysText(c *gin.Context) {

	var err error

	// ------------- Path parameter "text" -------------
	var text string

	err = runtime.BindStyledParameterWithOptions("simple", "text", c.Param("text"), &text, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter text: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSealSaysTextParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", c.Request.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "position" -------------

	err = runtime.BindQueryParameter("form", true, false, "position", c.Request.URL.Query(), &params.Position)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter position: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fontSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "fontSize", c.Request.URL.Query(), &params.FontSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fontSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fontColour" -------------

	err = runtime.BindQueryParameter("form", true, false, "fontColour", c.Request.URL.Query(), &params.FontColour)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fontColour: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "borderSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "borderSize", c.Request.URL.Query(), &params.BorderSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter borderSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "borderColour" -------------

	err = runtime.BindQueryParameter("form", true, false, "borderColour", c.Request.URL.Query(), &params.BorderColour)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter borderColour: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSealSaysText(c, text, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/seal", wrapper.GetSeal)
	router.GET(options.BaseURL+"/seal/says/:text", wrapper.GetSealSaysText)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RVTW/bMAz9KwK302DU2QeGIbdiwIYeBhRobkUPrE3bai3JlehuXuD/PlBOmri1k6zA",
	"Djs1FfWop/ee6DVkzjTOkuUAyzU06NEQk4//3Tqfk//qatf6S6nIYk4h87ph7SwsYSgqVyiuSGUY19UA",
	"hAS07HloyXeQgEVDsBx1hQRCVpHBoXOBbc2ypcbsHhLgrhFEYK9tCX2fbMBX+jfNEFpVOru3FMIrOEnb",
	"aUafEzDaatMaWC6eeGnLVJKPxApdM82p9C0WFTuFTVN38kOoaYMlzTAa+o3YkJXjr8E467LKOzNgH8kz",
	"JFC09r6DmynRCmf5FS4y/eI5dk8dZxz8WWkmmCNzwD8p/SWReds+fTnqW+OClkNm6FxuylOUlPw9YuO2",
	"/aSR7BqQSDM7AwnUVMg1vS4rnjaSsZyLPZZbileE9QwbxnJE5PkJ/bYYn39sJEPBu4Y8a4qrmSdkys95",
	"okECOp9cNtrQKi5OFBnL2FkzmfjjracClvAm3Q2ndMMrXeGAGZqg99hFaTw9tNpTHnWVhjsB3e0dZSwo",
	"AU9fW9vCxZLmWmo/JDVYq0CIdVDnlxcqkH+ML/KRfBhUf3+2OFtIY9eQxUbDEj7GpQQa5CpeJg0bGUuK",
	"komWKK5d5LCE78Qbv/ZH7/W0Brst6VMS+uTo3v3R1N+IVKFxNgx2flgsoqvOMtlIUEaUziLF9C7IPdd7",
	"kTnkTbxJVFNeRPpO9hfOG4wzXVuMWXwZ63GULwQsYUYVtg1Da4ygo2AKlUebO7ON+hCg6xjYADcCiKqn",
	"AbuQruWt9sccuMIurIY588yJ+JDEzr13NGzcZY59S4ceVvLvDD2+fTziTuk/GtEnAvY/MCdAnn/IT4aM",
	"zvnv0qwCdtqWKjhDXG0hB+L9EjCR977/EwAA//+4F+76yQkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
